
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/happybz/SpringCloud_Sell-config_repo.git
          username: happy_bz@qq.com
          password: 1120bzbz
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      expose: "*"